### ISSUE TITLE
Inconsistent Address Handling in IPSet

### ISSUE THREAD

**Issue by mjaustin2** [drkjam/netaddr#95] opened 2015-06-15 19:31 UTC
When a list of addresses is passed to IPSet, if that list contains host addresses with a CIDR mask and those items have adjacent networks, even if they are unmergable, the address spaces are changed to their correct network number and CIDR. Otherwise, they remain in the system in their original representation.

 

```
Python 2.7.9 (default, Apr 22 2015, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netaddr
>>> print netaddr.__version__
0.7.14
>>> networks = ['10.9.8.6/8', '172.16.1.2/16', '172.18.1.2/24', '192.168.0.0/24','192.168.2.3/23']
>>> set = netaddr.IPSet(networks)
>>> print set
IPSet(['10.9.8.6/8', '172.16.1.2/16', '172.18.1.2/24', '192.168.0.0/24', '192.168.2.3/23'])
>>> for i in set.iter_cidrs():
...     print i
...
10.9.8.6/8     <~~ Nothing adjacent so representation is unchanged.
172.16.1.2/16  <~~ Nothing adjacent so representation is unchanged.
172.18.1.2/24  <~~ Nothing adjacent so representation is unchanged.
192.168.0.0/24 <~~ Nothing to change
192.168.2.3/23 <~~ Nothing adjacent so representation is unchanged.

>>> networks = ['10.9.6.7/8', '11.0.0.1/8','172.0.0.9/16','172.1.1.1/16','192.168.1.2/24', '192.168.2.3/24']
>>> set = netaddr.IPSet(networks)
>>> print set
IPSet(['10.0.0.0/7', '172.0.0.0/15', '192.168.1.0/24', '192.168.2.0/24'])
>>> for i in set.iter_cidrs():
...     print i
...
10.0.0.0/7     <~~ Merged down to only address space
172.0.0.0/15   <~~ Merged down to only address space
192.168.1.0/24 <~~ Adjacent to another network space, so representation becomes network
192.168.2.0/24 <~~ Adjacent to another network space, so representation becomes network
```

**Comment by snordhausen** [comment] 2015-06-17 13:00
Personally, I see the "Merged down to only address space" case as the expected behavior. The "representation is unchanged" case just happens because I keep forgetting that

IPNetwork('172.16.1.2/16')

instead of

IPNetwork('172.16.0.0/16')

is possible, because I never use it.

I suggest we change the code so that the "Merged down to only address space" case is always enforced. This way, users will not be tricked into expecting a behavior that is not part of the feature-list.

**Comment by mjaustin2** [comment] 2015-06-19 03:25
I agree. I think the representing only the network number would be the expected behavior. This whole thing came about because I have one type of network equipment that spits out addresses with their CIDR mask. Then I use a script that uses netaddr to consolidate all of the networks down to into a one list and feed it to another device. The second piece of equipment chokes when it gets a non-network address with the CIDR mask.

I've worked around it using the following:

```
set = netaddr.IPSet(lines)
for net in set.iter_cidrs():
     print net.cidr
```

**Comment by snordhausen** [comment] 2015-06-19 12:10
Fixed in the next version.

**Closed by snordhausen** 2015-06-19 12:10 UTC
